# Generated by Django 3.1.5 on 2021-01-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Learning_System.student'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Learning_System.course'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Learning_System.mentor'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Learning_System.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='git_link',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
