# Generated by Django 3.1.6 on 2021-02-01 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ManyToManyField(to='learning_management.Course')),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternate_mobile_number', models.CharField(default=None, max_length=13, null=True)),
                ('relation_with_alt_num', models.CharField(default=None, max_length=30, null=True)),
                ('current_location', models.CharField(default=None, max_length=50, null=True)),
                ('current_address', models.CharField(default=None, max_length=100, null=True)),
                ('git_link', models.CharField(max_length=60)),
                ('year_of_exp', models.IntegerField(default=None)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_management.course')),
                ('mentor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_management.mentor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning_management.student')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.FloatField(default=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_management.course')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_management.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_management.student')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(default=None, max_length=30, null=True)),
                ('degree', models.CharField(default=None, max_length=20, null=True)),
                ('degree_stream', models.CharField(default=None, max_length=50, null=True)),
                ('percentage', models.FloatField(default=None, null=True)),
                ('from_date', models.DateField(default=None, null=True)),
                ('till', models.DateField(default=None, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning_management.student')),
            ],
        ),
    ]
