# Generated by Django 3.1.6 on 2021-02-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_management', '0003_auto_20210202_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='student_id',
        ),
    ]
