# Generated by Django 3.1.6 on 2021-02-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_management', '0004_auto_20210203_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student',
        ),
    ]
