# Generated by Django 3.1.5 on 2021-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('confirm_password', models.CharField(default=None, max_length=20, null=True)),
                ('mob_no', models.CharField(default=None, max_length=13, null=True)),
                ('role', models.CharField(choices=[('Mentor', 'Mentor'), ('Engineer', 'Engineer'), ('Admin', 'Admin')], max_length=20)),
            ],
        ),
    ]
