# Generated by Django 3.1.5 on 2021-02-01 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_first_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
    ]
