# Generated by Django 3.1.5 on 2021-02-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=False),
        ),
    ]
